---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- path: content/questions
  label: Questions
  create: all
- path: content
  label: Pages
  create: all
- path: content/modules
  label: Modules
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.43'
